id: P003115
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:41:16.157381
source_metadata:
  id: bdr:W1KG25716
  title: དཔྱད་རྩོམ་ཤེས་རབ་སྣང་བ།
  author: ''
  volumes:
    fb1e6787ff2b4129b554f9cf3339e990:
      image_group_id: I1KG25718
      title: ''
      volume_number: 1
      total_pages: 160
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
