id: P003115
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25716
  title: དཔྱད་རྩོམ་ཤེས་རབ་སྣང་བ།
  author: ''
  volumes:
    fb1e6787ff2b4129b554f9cf3339e990:
      image_group_id: I1KG25718
      title: ''
      volume_number: 1
      total_pages: 160
      base_file: v001.txt
